name: HealFeed
main: viskaraze\HealFeed\Main
version: 1.0.0
api:
- 4.0.0
author: VisKa_RaZe

commands:
  feed:
    description: Feed yourslef to max !
    permission: HealFeed.feed.use
  heal:
    description: Heal yourslef to max !
    permission: HealFeed.heal.use
permissions:
  HealFeed.feed.use:
    description: Permission to feed yourself
    default: op
  HealFeed.heal.use:
    description: Permission to heal yourself
    default: op
